### ISSUE TITLE
can not migrate DB in redmine3.2.x

### ISSUE THREAD

**Issue by archonwang** [kexun/weeklyreport#1]
the plugin can not be installed in redmine 3.2.x when I migrate DB

> Migrating weeklyreport (Weeklyreport plugin)...
> rake aborted!
> uninitialized constant CreateWeeklyreports
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/inflector/methods.rb:261:in `const_get'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/inflector/methods.rb:261:in`block in constantize'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/inflector/methods.rb:259:in `each'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/inflector/methods.rb:259:in`inject'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/inflector/methods.rb:259:in `constantize'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/core_ext/string/inflections.rb:66:in`constantize'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:778:in `load_migration'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:773:in`migration'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:1051:in`use_transaction?'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:961:in `rescue in block in migrate'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:958:in`block in migrate'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `each'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in`migrate'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:823:in `up'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:801:in`migrate'
> /opt/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
> /opt/redmine/lib/redmine/plugin.rb:453:in`migrate'
> /opt/redmine/lib/redmine/plugin.rb:467:in `block in migrate'
> /opt/redmine/lib/redmine/plugin.rb:466:in`each'
> /opt/redmine/lib/redmine/plugin.rb:466:in `migrate'
> /opt/redmine/lib/tasks/redmine.rake:127:in`block (3 levels) in <top (required)>'
> Tasks: TOP => redmine:plugins:migrate
> (See full trace by running task with --trace)

**Comment by kexun** [comment]
你好 这个插件时我3年前实习的时候做的，当时的开发环境是redmine2.3.3，你可以在这个版本下试试，我觉得应该是版本问题。

**Comment by archonwang** [comment]
@kexun  ,
OK. Thanks.
